- apiVersion: v1
  data:
    calico_backend: bird
    cni_network_config: "{\n  \"name\": \"k8s-pod-network\",\n  \"cniVersion\": \"\
      0.3.0\",\n  \"plugins\": [\n    {\n      \"type\": \"calico\",\n      \"log_level\"\
      : \"info\",\n      \"datastore_type\": \"kubernetes\",\n      \"nodename\":\
      \ \"__KUBERNETES_NODE_NAME__\",\n      \"mtu\": __CNI_MTU__,\n      \"ipam\"\
      : {\n        \"type\": \"calico-ipam\"\n      },\n      \"policy\": {\n    \
      \      \"type\": \"k8s\"\n      },\n      \"kubernetes\": {\n          \"kubeconfig\"\
      : \"__KUBECONFIG_FILEPATH__\"\n      }\n    },\n    {\n      \"type\": \"portmap\"\
      ,\n      \"snat\": true,\n      \"capabilities\": {\"portMappings\": true}\n\
      \    }\n  ]\n}"
    typha_service_name: none
    veth_mtu: '1440'
  kind: ConfigMap
  metadata:
    name: calico-config
    namespace: kube-system
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: felixconfigurations.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: FelixConfiguration
      plural: felixconfigurations
      singular: felixconfiguration
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: ipamblocks.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: IPAMBlock
      plural: ipamblocks
      singular: ipamblock
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: blockaffinities.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: BlockAffinity
      plural: blockaffinities
      singular: blockaffinity
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: ipamhandles.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: IPAMHandle
      plural: ipamhandles
      singular: ipamhandle
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: ipamconfigs.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: IPAMConfig
      plural: ipamconfigs
      singular: ipamconfig
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: bgppeers.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: BGPPeer
      plural: bgppeers
      singular: bgppeer
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: bgpconfigurations.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: BGPConfiguration
      plural: bgpconfigurations
      singular: bgpconfiguration
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: ippools.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: IPPool
      plural: ippools
      singular: ippool
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: hostendpoints.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: HostEndpoint
      plural: hostendpoints
      singular: hostendpoint
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: clusterinformations.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: ClusterInformation
      plural: clusterinformations
      singular: clusterinformation
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: globalnetworkpolicies.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: GlobalNetworkPolicy
      plural: globalnetworkpolicies
      singular: globalnetworkpolicy
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: globalnetworksets.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: GlobalNetworkSet
      plural: globalnetworksets
      singular: globalnetworkset
    scope: Cluster
    version: v1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: networkpolicies.crd.projectcalico.org
  spec:
    group: crd.projectcalico.org
    names:
      kind: NetworkPolicy
      plural: networkpolicies
      singular: networkpolicy
    scope: Namespaced
    version: v1
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: calico-kube-controllers
  rules:
  - apiGroups:
    - ''
    resources:
    - nodes
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - ''
    resources:
    - pods
    verbs:
    - get
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ippools
    verbs:
    - list
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - blockaffinities
    - ipamblocks
    - ipamhandles
    verbs:
    - get
    - list
    - create
    - update
    - delete
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - clusterinformations
    verbs:
    - get
    - create
    - update
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: calico-kube-controllers
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: calico-kube-controllers
  subjects:
  - kind: ServiceAccount
    name: calico-kube-controllers
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: calico-node
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - nodes
    - namespaces
    verbs:
    - get
  - apiGroups:
    - ''
    resources:
    - endpoints
    - services
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - ''
    resources:
    - nodes/status
    verbs:
    - patch
    - update
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    verbs:
    - watch
    - list
  - apiGroups:
    - ''
    resources:
    - pods
    - namespaces
    - serviceaccounts
    verbs:
    - list
    - watch
  - apiGroups:
    - ''
    resources:
    - pods/status
    verbs:
    - patch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - globalfelixconfigs
    - felixconfigurations
    - bgppeers
    - globalbgpconfigs
    - bgpconfigurations
    - ippools
    - ipamblocks
    - globalnetworkpolicies
    - globalnetworksets
    - networkpolicies
    - clusterinformations
    - hostendpoints
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ippools
    - felixconfigurations
    - clusterinformations
    verbs:
    - create
    - update
  - apiGroups:
    - ''
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - bgpconfigurations
    - bgppeers
    verbs:
    - create
    - update
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - blockaffinities
    - ipamblocks
    - ipamhandles
    verbs:
    - get
    - list
    - create
    - update
    - delete
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ipamconfigs
    verbs:
    - get
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - blockaffinities
    verbs:
    - watch
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: calico-node
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: calico-node
  subjects:
  - kind: ServiceAccount
    name: calico-node
    namespace: kube-system
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      k8s-app: calico-node
    name: calico-node
    namespace: kube-system
  spec:
    selector:
      matchLabels:
        k8s-app: calico-node
    template:
      metadata:
        annotations:
          scheduler.alpha.kubernetes.io/critical-pod: ''
        labels:
          k8s-app: calico-node
      spec:
        containers:
        - env:
          - name: DATASTORE_TYPE
            value: kubernetes
          - name: WAIT_FOR_DATASTORE
            value: 'true'
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CALICO_NETWORKING_BACKEND
            valueFrom:
              configMapKeyRef:
                key: calico_backend
                name: calico-config
          - name: CLUSTER_TYPE
            value: k8s,bgp
          - name: IP
            value: autodetect
          - name: CALICO_IPV4POOL_IPIP
            value: Always
          - name: FELIX_IPINIPMTU
            valueFrom:
              configMapKeyRef:
                key: veth_mtu
                name: calico-config
          - name: CALICO_IPV4POOL_CIDR
            value: 192.168.0.0/16
          - name: CALICO_DISABLE_FILE_LOGGING
            value: 'true'
          - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
            value: ACCEPT
          - name: FELIX_IPV6SUPPORT
            value: 'false'
          - name: FELIX_LOGSEVERITYSCREEN
            value: info
          - name: FELIX_HEALTHENABLED
            value: 'true'
          image: calico/node:v3.6.4
          livenessProbe:
            failureThreshold: 6
            httpGet:
              host: localhost
              path: /liveness
              port: 9099
            initialDelaySeconds: 10
            periodSeconds: 10
          name: calico-node
          readinessProbe:
            exec:
              command:
              - /bin/calico-node
              - -bird-ready
              - -felix-ready
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
            readOnly: true
          - mountPath: /run/xtables.lock
            name: xtables-lock
            readOnly: false
          - mountPath: /var/run/calico
            name: var-run-calico
            readOnly: false
          - mountPath: /var/lib/calico
            name: var-lib-calico
            readOnly: false
        hostNetwork: true
        initContainers:
        - command:
          - /opt/cni/bin/calico-ipam
          - -upgrade
          env:
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CALICO_NETWORKING_BACKEND
            valueFrom:
              configMapKeyRef:
                key: calico_backend
                name: calico-config
          image: calico/cni:v3.6.4
          name: upgrade-ipam
          volumeMounts:
          - mountPath: /var/lib/cni/networks
            name: host-local-net-dir
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
        - command:
          - /install-cni.sh
          env:
          - name: CNI_CONF_NAME
            value: 10-calico.conflist
          - name: CNI_NETWORK_CONFIG
            valueFrom:
              configMapKeyRef:
                key: cni_network_config
                name: calico-config
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CNI_MTU
            valueFrom:
              configMapKeyRef:
                key: veth_mtu
                name: calico-config
          - name: SLEEP
            value: 'false'
          image: calico/cni:v3.6.4
          name: install-cni
          volumeMounts:
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
          - mountPath: /host/etc/cni/net.d
            name: cni-net-dir
        nodeSelector:
          beta.kubernetes.io/os: linux
        serviceAccountName: calico-node
        terminationGracePeriodSeconds: 0
        tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
        volumes:
        - hostPath:
            path: /lib/modules
          name: lib-modules
        - hostPath:
            path: /var/run/calico
          name: var-run-calico
        - hostPath:
            path: /var/lib/calico
          name: var-lib-calico
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
        - hostPath:
            path: /opt/cni/bin
          name: cni-bin-dir
        - hostPath:
            path: /etc/cni/net.d
          name: cni-net-dir
        - hostPath:
            path: /var/lib/cni/networks
          name: host-local-net-dir
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: calico-node
    namespace: kube-system
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      scheduler.alpha.kubernetes.io/critical-pod: ''
    labels:
      k8s-app: calico-kube-controllers
    name: calico-kube-controllers
    namespace: kube-system
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          k8s-app: calico-kube-controllers
        name: calico-kube-controllers
        namespace: kube-system
      spec:
        containers:
        - env:
          - name: ENABLED_CONTROLLERS
            value: node
          - name: DATASTORE_TYPE
            value: kubernetes
          image: calico/kube-controllers:v3.6.4
          name: calico-kube-controllers
          readinessProbe:
            exec:
              command:
              - /usr/bin/check-status
              - -r
        nodeSelector:
          beta.kubernetes.io/os: linux
        serviceAccountName: calico-kube-controllers
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: calico-kube-controllers
    namespace: kube-system
