apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/metallb/frr-k8s/config/default/?timeout=120&ref=v0.0.17
- ../native
patchesStrategicMerge:
- speaker-patch.yaml
- controller-patch.yaml
patches:
  - path: ignore-ns.yaml
namespace: metallb-system
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: metallb-system:speaker
    path: clusterrole-patch.yaml
