apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: metallb-system
  name: test-bgp-router
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-bgp-router
  template:
    metadata:
      labels:
        app: test-bgp-router
    spec:
      containers:
      - name: test-bgp-router
        image: metallb/test-bgp-router:latest
        env:
        - name: METALLB_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: bird
          containerPort: 1179
        - name: quagga
          containerPort: 179
        - name: gobgp
          containerPort: 2179
        - name: http
          containerPort: 7472
        securityContext:
          capabilities:
            add:
            - net_admin
            - sys_admin

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-bird
spec:
  ports:
  - name: bgp
    port: 179
    protocol: TCP
    targetPort: bird
  selector:
    app: test-bgp-router
  clusterIP: 10.96.0.100

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-quagga
spec:
  ports:
  - name: bgp
    port: 179
    protocol: TCP
    targetPort: quagga
  selector:
    app: test-bgp-router
  clusterIP: 10.96.0.101

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-gobgp
spec:
  ports:
  - name: bgp
    port: 179
    protocol: TCP
    targetPort: gobgp
  selector:
    app: test-bgp-router
  clusterIP: 10.96.0.102

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: test-bgp-router
  type: NodePort
