apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    peers:
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.0.0.100
    address-pools:
    - name: my-ip-space
      avoid-buggy-ips: true
      cidr:
      - 198.51.100.0/24
      advertisements:
      -
