apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    # Temporarily disabled due to bug #142
    # - my-asn: 64512
    #   peer-asn: 64512
    #   peer-address: 10.96.0.100
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.96.0.101
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.96.0.102
    address-pools:
    - name: my-ip-space
      protocol: bgp
      cidr:
      - 198.51.100.0/24
