apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/metallb/frr-k8s/config/prometheus/?timeout=120&ref=v0.0.17
- ../prometheus-native
patchesStrategicMerge:
- speaker-patch.yaml
- controller-patch.yaml
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: metallb-system:speaker
    path: clusterrole-patch.yaml
patches:
  - path: ignore-ns.yaml
  - path: ignore-prom-role.yaml
  - path: ignore-prom-rolebinding.yaml
  - path: relabel-metrics.yaml
    target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: frr-k8s-metrics-monitor
namespace: metallb-system
