apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/metallb.io_ipaddresspools.yaml
- bases/metallb.io_bgppeers.yaml
- bases/metallb.io_bfdprofiles.yaml
- bases/metallb.io_bgpadvertisements.yaml
- bases/metallb.io_l2advertisements.yaml
- bases/metallb.io_communities.yaml
- bases/metallb.io_servicel2statuses.yaml

patches:
- path: patches/crd-conversion-patch-bgppeers.yaml
  target:
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
