# permissions for end users to view addresspools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addresspools-viewer-role
rules:
- apiGroups:
  - metallb.metallb.io
  resources:
  - addresspools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metallb.metallb.io
  resources:
  - addresspools/status
  verbs:
  - get
