# permissions for end users to edit addresspools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addresspools-editor-role
rules:
- apiGroups:
  - metallb.metallb.io
  resources:
  - addresspools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metallb.metallb.io
  resources:
  - addresspools/status
  verbs:
  - get
