name: "install-deps"
description: "Install deps required for metallb CI"

runs:
  using: "composite"
  steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/setup-go@v2
      with:
        go-version: "1.17.1"

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip arping ndisc6
        sudo pip3 install invoke semver pyyaml
        GO111MODULE="on" go get sigs.k8s.io/kind@v0.11.1
        go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0

    - name: Download MetalLB images
      uses: actions/download-artifact@v3
      with:
        name: metallb-images
        path: metallb-images

    - name: Load MetalLB images
      shell: bash
      working-directory: metallb-images
      run: |
        docker load -i speaker.tar
        docker load -i controller.tar
        docker load -i mirror-server.tar
