baseurl = "/"
languageCode = "en-us"
title = "MetalLB, bare metal load-balancer for Kubernetes"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	description = "MetalLB, bare metal load-balancer for Kubernetes"
	copyright = "Released under the Apache license v2.0"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/google/metallb"

	version = "tip"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
    twitter = ""
    github  = "google/metallb"
    email   = ""


[[menu.main]]
	name   = "Welcome"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Tutorial"
	url    = "tutorial/"
	weight = 10

[[menu.main]]
	name   = "Installation"
	url    = "installation/"
	weight = 20

[[menu.main]]
	name   = "Usage"
	url    = "usage/"
	weight = 30

[[menu.main]]
	name   = "Design"
	url    = "design/"
	weight = 40

[[menu.main]]
	name   = "Hacking"
	url    = "hacking/"
	weight = 50

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 60

[[menu.main]]
    name   = "Release Notes"
    url    = "release-notes/"
    weight = 70

[[menu.main]]
    name   = "Community"
    url    = "community/"
    weight = 80

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
