baseurl = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "MetalLB, bare metal load-balancer for Kubernetes"
theme = "docdock"

[params]
	# General information
    editURL = "https://github.com/google/metallb/edit/master/website/content/"
	description = "MetalLB, bare metal load-balancer for Kubernetes"
    disableNavChevron = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<hr>"
name = "<i class='fa fa-github'></i> Github repo"
url = "https://github.com/google/metallb"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-envelope-open-o'></i> Mailing list"
url = "https://groups.google.com/forum/#!forum/metallb-users"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-slack'></i> Slack"
url = "https://kubernetes.slack.com/messages/metallb"
weight = 30

[[menu.shortcuts]]
name = "<i class='fa fa-copyright'></i> License"
url = "https://github.com/google/metallb/blob/master/LICENSE"
weight = 40
