name: Vuln check
on:
  schedule: 
    - cron: '0 */6 * * *'

permissions: 
  security-events: write

jobs:
  vuln-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Golang Vulncheck
        uses: Templum/govulncheck-action@v0.10.1

