{{- if .Values.speaker.excludeInterfaces.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-excludel2
  namespace: {{ .Release.Namespace | quote }}
data:
  excludel2.yaml: |
    announcedInterfacesToExclude:
    - ^docker.*
    - ^cbr.*
    - ^dummy.*
    - ^virbr.*
    - ^lxcbr.*
    - ^veth.*
    - ^lo$
    - ^cali.*
    - ^tunl.*
    - ^flannel.*
    - ^kube-ipvs.*
    - ^cni.*
    - ^nodelocaldns.*
{{- end }}